### ISSUE TITLE
An error occurred when executing deepstream-app -c deepstream_app_config.txt 

### ISSUE THREAD

**Issue by JasonChao-yue** [marcoslucianops/DeepStream-Yolo#294]
root@c9f6739d9a42:/opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo-master# deepstream-app -c deepstream_app_config.txt 
Deserialize yoloLayer plugin: yolo
0:00:01.324753165   644 0x5639ed61d930 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 1]: deserialized trt engine from :/opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo-master/model_b1_gpu0_fp32.engine
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 5
0   INPUT  kFLOAT data            3x640x640       
1   OUTPUT kFLOAT num_detections  1               
2   OUTPUT kFLOAT detection_boxes 25200x4         
3   OUTPUT kFLOAT detection_scores 25200           
4   OUTPUT kFLOAT detection_classes 25200           

0:00:01.325666424   644 0x5639ed61d930 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2012> [UID = 1]: Use deserialized engine model: /opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo-master/model_b1_gpu0_fp32.engine
ERROR: nvdsinfer_backend.cpp:38 cudaStreamCreateWithPriority failed, cuda err_no:222, err_str:cudaErrorUnsupportedPtxVersion
0:00:01.361201648   644 0x5639ed61d930 ERROR                nvinfer gstnvinfer.cpp:640:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::allocateResource() <nvdsinfer_context_impl.cpp:293> [UID = 1]: Failed to create preprocessor cudaStream
0:00:01.361227628   644 0x5639ed61d930 ERROR                nvinfer gstnvinfer.cpp:640:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::preparePreprocess() <nvdsinfer_context_impl.cpp:1029> [UID = 1]: preprocessor allocate resource failed
ERROR: nvdsinfer_context_impl.cpp:1275 Infer Context prepare preprocessing resource failed., nvinfer error:NVDSINFER_TENSORRT_ERROR
0:00:01.378706506   644 0x5639ed61d930 WARN                 nvinfer gstnvinfer.cpp:846:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:01.378717319   644 0x5639ed61d930 WARN                 nvinfer gstnvinfer.cpp:846:gst_nvinfer_start:<primary_gie> error: Config file path: /opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo-master/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_TENSORRT_ERROR
** ERROR: <main:716>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: gstnvinfer.cpp(846): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo-master/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_TENSORRT_ERROR
App run failed
@marcoslucianops  Tankes!

**Comment by marcoslucianops** [comment]
What is your CUDA and Driver version? And what is the version of the DeepStream you are trying to run?

**Comment by JasonChao-yue** [comment]
> What is your CUDA and Driver version? And what is the version of the DeepStream you are trying to run?

The cuda version is too low. It was changed to 11.7
thankes!

**Comment by marcoslucianops** [comment]
Did you solve the problema by upgrading the CUDA?

**Comment by JasonChao-yue** [comment]
> Did you solve the problem by upgrading the CUDA?

I also upgraded the driver version to 515.43.04, and the problem disappeared
